### PR TITLE
Updated hoek dependency

### PR DESCRIPTION
**Pull request by iniva**
This PR updates Hoek to version 6.

Version 5.0.4 was not maintained anymore.

### CODE REVIEW

**Comment by danielb2** [comment]
thank you :)

**Comment by iniva** [comment]
Are you planning on making a release with something else? If not, could you please publish a patch release with this?

**Comment by danielb2** [comment]
Yes, I will publish a patch release

**Comment by danielb2** [comment]
https://www.npmjs.com/package/blipp/v/3.1.3

**Pull request merged**
