### PR TITLE
Display HTTP methods in the same colors as hapi lout does

### PR DESCRIPTION
**Pull request by cbmono**
Display HTTP methods in the same colors as [hapi lout](https://github.com/hapijs/lout) does. See screenshots:

image

image

### CODE REVIEW

**Comment by danielb2** [comment]
I'm not sure I see a specific advantage to doing this. Also, I find the blue on black very hard to read.

**Comment by cbmono** [comment]
What about cyan instead of blue?
image

If you have bigger apps where you have 25+ end-points (like we do), it's useful to be able to spot quickly the different HTTP methods.

**Comment by danielb2** [comment]
I've contemplated this.  I considered whether I should allow the colors to be configurable, but I think that does add some bloat to the code that has to be maintained.

As for this PR, coverage shouldn't have to be turned off, and I don't like the `_Chalk` variable.

I'm still on the fence about making colors optional.  Perhaps a `colors` options for each method.
``` javascript
server.register({ register: Blipp, options: { colors: { get: 'blue' } } ...
```

**Comment by danielb2** [comment]
closing due to lack of response

**Pull request closed without merging**
