### PR TITLE
Fix displaying auth scope

### PR DESCRIPTION
**Pull request by Dennis-Emmental**
#37

### CODE REVIEW

**Comment by Dennis-Emmental** [comment]
hm~ Checking code coverage is odd. 
I think codes of that lines are executed.

**Comment by danielb2** [comment]
the coverage reporting tool is accurate. Want to check it again ?

**Comment by Dennis-Emmental** [comment]
Test result in my local mac os is following

```
$ npm run test

> blipp@3.1.1 test /Users/dennis/github/blipp
> lab -a code -v -t 100 -L

routes
  ✔ 1) print route information (32 ms and 4 assertions)
  ✔ 2) gets route information (9 ms and 3 assertions)
required: tester1 forbidden: tester3 selection: tester2
required: tester1 forbidden: tester3 selection: tester2
  ✔ 3) gets route information with auth (8 ms and 5 assertions)
required: tester1 forbidden: tester3 selection: tester2
required: tester1 forbidden: tester3 selection: tester2
  ✔ 4) gets route information with scope (7 ms and 5 assertions)
required: tester1 forbidden: tester3 selection: tester2
required: tester1 forbidden: tester3 selection: tester2
  ✔ 5) gets route information with default (11 ms and 4 assertions)
  ✔ 6) fails with invalid options (7 ms and 2 assertions)


6 tests complete
Test duration: 81 ms
Assertions count: 23 (verbosity: 3.83)
No global variable leaks detected
Coverage: 95.95% (6/148)
lib/index.js missing coverage on line(s): 126, 127, 128, 129, 130, 131
Code coverage below threshold: 95.95 < 100
Linting results: No issues
```

I inserted debug message like following
```
125:        if (route.settings.auth && route.settings.auth.access) {
126:            const required = route.settings.auth.access[0].scope.required ?
127:                `required: ${route.settings.auth.access[0].scope.required.toString()} ` : '';
128:            const forbidden = route.settings.auth.access[0].scope.forbidden ?
129:                `forbidden: ${route.settings.auth.access[0].scope.forbidden.toString()} ` : '';
130:            const selection = route.settings.auth.access[0].scope.selection ?
131:                `selection: ${route.settings.auth.access[0].scope.selection.toString()}` : '';

            authScope = `${required}${forbidden}${selection}`;
            console.log(authScope);
        }
```

I think those lines are executed.

**Comment by danielb2** [comment]
While the lines may all be executed, are all the variations of the conditionals executed ?

Those are all ternaries.

I recommend you use [Hoek.reach](https://github.com/hapijs/hoek/blob/HEAD/API.md#reachobj-chain-options) to make this simpler.

`Hoek.reach(route, 'settings.auth.access.0.scope.selection', { default: '' });`

For example

**Comment by Dennis-Emmental** [comment]
Ok. I understand. 

I will add test cases and rewrite my codes. :)

**Comment by danielb2** [comment]
Thank you @Dennis-Emmental

**Comment by treyhuffine** [comment]
@danielb2 has this change been published? I'm still seeing the old code in v3.1.1 on npm and getting the error.

Thanks for the maintaining the package, it's great.

**Comment by danielb2** [comment]
I think I had something else in mind to release at the same time, but obviously that hasn't happened. I'lll do it now :)  thank you for the reminder

**Comment by danielb2** [comment]
ok, done! sorry for the delay

**Comment by treyhuffine** [comment]
Thanks! Works great

**Pull request merged**
